import React from 'react';
import {Link} from "react-router-dom";
import {Col, Container, Row} from "react-bootstrap";

class Content extends React.Component {
    render() {
        return (
            <Container>
                <Row>
                    <Col sm={8}>
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                    </Col>
                    <Col sm={4}>
                        sABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbsABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ABHKSAFNAJKSNDAJKSVJDAJScbsdhjvbfdakvdahvbs
                        ad
                    </Col>
                </Row>
            </Container>
        );
    }
}

export default Content;
